import { auth } from '@/services/firebase'
import { useAppSelector } from '@/store'
import { routeNames } from '@/utils/globalConstants'
import { signOut } from 'firebase/auth'
import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  const user = useAppSelector(state => state.user)
  console.log(user)

  const logout = async () => {
    try {
      await signOut(auth)
      router.push(routeNames.LOGIN)
    } catch (e: any) {
      console.log(e.message)
    }
  }

  return (
    <div>
      <Head>
        <title>Summer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='min-h-screen flex justify-center items-center'>
        <h2>Welcome User</h2>
        <button onClick={logout}>Sign Out</button>
      </main>
    </div>
  )
}
